### ISSUE TITLE
If path contain character "é", wiki is not saved (Error: path does not exist)

### ISSUE THREAD

**Issue by FredericLespez** [TiddlyWiki/TiddlyFox#48] opened 2017-05-05 14:00 UTC
Context : Debian Stretch / Firefox 52.0.2 / TiddlyWiki for Firefox 2.0.1 / Locale fr_FR.utf8

My Tiddlywiki is saved under the following path:
`/home/fred/Privé/tiddlywiki.html`

Since I upgraded the TiddlyWiki extension for Firefox to the 2.0.1 version,  I cannot save anymore.
The extension tries to save under the following path:
`/home/fred/PrivÃ©/tiddlywiki.html`

Notice that the character "`é`" in the path has been changed into "`Ã©`".
If I move tiddlywiki file to this path : `/home/fred/tiddlywiki.html`, saving works again.

Here is the error message (visible in Firefox STDOUT not in the JS console):
```
messageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/remote/parent.js:96:37

console.error: tiddlywiki: 
  Message: Error: path does not exist: /home/fred/PrivÃ©/tiddlywiki.html
  Stack:
    friendlyError@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:62:12
open@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/io/file.js:150:13
```

**Comment by YakovL** [comment] 2019-01-08 21:48
this is presumably a duplicate of #38

**Comment by FredL69** [comment] 2019-01-09 07:13
You are right.

Duplicate of #38

**Closed by FredL69** 2019-01-09 07:13 UTC
